'use strict'

angular
  .module('nexusApp', [])

###
# Welcome to the new js2coffee 2.0, now
# rewritten to use the esprima parser.
# try it out!
###

console.log 'Hello World!'
# Include http module.
http = require('http') #Getting undefined reference 'require' error since NODE isnt clientside
# Create the server. Function passed as parameter is called on every request made.
# request variable holds all request parameters
# response variable allows you to do anything with response sent to the client.
http.createServer((request, response) ->
  # Attach listener on end event.
  # This event is called when client sent all data and is waiting for response.
  request.on 'end', ->
    # Write headers to the response.
    # 200 is HTTP status code (this one means success)
    # Second parameter holds header fields in object
    # We are sending plain text, so Content-Type should be text/plain
    response.writeHead 200, 'Content-Type': 'text/plain'
    # Send data and end response.
    response.end 'Hello HTTP!'
    return
  # Listen on the 9000 port.
  return
).listen 9000

# ---
# generated by js2coffee 2.0.3